[pytest]
addopts = -ra --cov=Day_24_Pandas_Advanced.pandas_adv --cov=Day_25_Data_Cleaning.data_cleaning --cov=Day_26_Statistics.stats --cov-report=term-missing --cov-fail-under=40
testpaths = tests
filterwarnings =
	ignore:pkg_resources is deprecated as an API:UserWarning
	ignore:In the future `np.object` will be defined as the corresponding NumPy scalar:FutureWarning:keras
	ignore:__array__ implementation doesn't accept a copy keyword:DeprecationWarning
	ignore:'penalty' was deprecated in version 1.8 and will be removed in 1.10:FutureWarning:sklearn.linear_model._logistic
