blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/saint2706/Coding-For-MBA/discussions/new?category=q-a
    about: Have a question? Start a discussion!
  - name: Show and Tell
    url: https://github.com/saint2706/Coding-For-MBA/discussions/new?category=show-and-tell
    about: Share what you've built with the community
