name: Lesson Improvement
description: Suggest enhancements to existing lessons, datasets, or exercises
title: "[Lesson]: "
labels: ["lesson-improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Help us level up the curriculum! Share context on what could be clearer, more engaging, or more accurate.

  - type: dropdown
    id: lesson
    attributes:
      label: Which lesson needs improvement?
      description: Select the primary lesson or resource you want to improve
      options:
        - Day 01-20 (Python Foundations)
        - Day 21-39 (Data Workflows)
        - Day 40-54 (ML Fundamentals)
        - Day 55-67 (Advanced ML & MLOps)
        - Cross-cutting resource (datasets, tooling, docs)
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: What should change and why?
      description: Describe the learner pain point or opportunity
      placeholder: Learners get stuck when...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed updates
      description: Share the content, code, or assets you'd like to see updated
      placeholder: We could improve this by...
    validations:
      required: true

  - type: textarea
    id: artifacts
    attributes:
      label: Supporting materials
      description: Link to notebooks, screenshots, or references that back up the suggestion
      placeholder: Related notebook: ...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Are you able to help with the update?
      options:
        - label: I can submit a pull request for this improvement
