title: Coding for MBA
email: ''
description: >-
  Lesson library and curriculum roadmap for the Coding for MBA program.
baseurl: ""
url: ""
permalink: pretty
theme: just-the-docs
search_enabled: true
color_scheme: light

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache

nav_order: 1

aux_links:
  "View on GitHub":
    - https://github.com/saint2706/Coding-For-MBA
  "Saint2706 Pages":
    - https://saint2706.github.io/Coding-For-MBA/

footer_content: >-
  &copy; {current_year} Coding for MBA. Released under the MIT License.

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
