name: Python CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.ipynb'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'pytest.ini'
      - 'Makefile'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.ipynb'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'pytest.ini'
      - 'Makefile'
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Lint and format checks
      run: make lint

    - name: Test with pytest
      run: pytest
