name: Lint and Format Check

on:
  workflow_dispatch:  # Allow manual trigger
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.ipynb'
      - '**.md'
      - 'pyproject.toml'
      - 'Makefile'
      - '.github/workflows/lint.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check code formatting

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run lint checks
      run: make lint
